# Generated by Django 6.0.3 on 2026-03-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField()),
                ('objet', models.CharField(max_length=500)),
                ('corps', models.TextField()),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('destinataires', models.ManyToManyField(related_name='recus', to='discovery.collaborateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoyes', to='discovery.collaborateur')),
            ],
        ),
    ]
