# Generated by Django 6.0.3 on 2026-03-17 18:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discovery.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('objet', models.CharField(max_length=500)),
                ('corps', models.TextField()),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('destinataires', models.ManyToManyField(related_name='recus', to='discovery.collaborateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoyes', to='discovery.collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='MessageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discovery.folder')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='discovery.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='discovery_m_message_bad8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['in_reply_to'], name='discovery_m_in_repl_9bdf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='discovery_m_search__3045aa_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='messagefolder',
            unique_together={('message', 'folder')},
        ),
    ]
