# Generated by Django 6.0.3 on 2026-03-14 10:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='discovery_m_message_bad8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['in_reply_to'], name='discovery_m_in_repl_9bdf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='discovery_m_search__3045aa_gin'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='discovery.collaborateur'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discovery.folder'),
        ),
        migrations.AddField(
            model_name='messagefolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discovery.folder'),
        ),
        migrations.AddField(
            model_name='messagefolder',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='discovery.message'),
        ),
        migrations.AlterUniqueTogether(
            name='messagefolder',
            unique_together={('message', 'folder')},
        ),
    ]
