# Generated by Django 6.0.3 on 2026-03-12 22:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='discovery_m_message_bad8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['in_reply_to'], name='discovery_m_in_repl_9bdf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='discovery_m_search__3045aa_gin'),
        ),
    ]
