# Generated by Django 6.0.3 on 2026-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_message_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['date'], name='discovery_m_date_51d1b5_idx'),
        ),
    ]
