# Generated by Django 6.0.3 on 2026-03-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_remove_folder_owner_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
