# Generated by Django 6.0.3 on 2026-03-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_delete_attachment'),
        ('discovery', '0005_populate_search_vector'),
    ]

    operations = [
    ]
