# Generated by Django 6.0.3 on 2026-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_merge_20260316_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
